<style>
    #advanced-settings-div {
        display: none;
    }
    #campaign-distribution {
        width: 110px !important;
    }
    #campaign-type {
        width: 110px !important;
    }
</style>
<?php
/* @var $pf PageFragment_FormAuto */
?>


<div class="settings">

    <h3>Campaign Settings</h3>

    <div class="setup">

        <div class="leftinfo">

            <p class="top"><span>Campaign Name: <?php Helper_Tooltip::toolTipFromWP('what-is-campaign-name'); ?></span><br>
                <?php echo $pf->getHtmlForNamedElementFull('name', array('class' => 'full-width')); ?>
            </p>
            <p><span>Notes: (Optional) <?php Helper_Tooltip::toolTipFromWP('what-is-the-campaign-notes'); ?></span><br>
                <?php echo $pf->getHtmlForNamedElementFull('notes', array('class' => 'full-width')); ?>
            </p>

        </div><!--leftinfo-->

        <div class="rightinfo">
            <p style="float: left;"><span>Campaign Type <?php Helper_Tooltip::toolTipFromWP('what-is-the-campaign-status'); ?></span><br>
                <?php echo $pf->getHtmlForNamedElementFull('campaign_type', array('style' => 'width: 100px;', 'id' => 'campaign-type')); ?>
            </p>
            <p style="float: left;"> &nbsp; &nbsp; <span>Campaign Cap <?php Helper_Tooltip::toolTipFromWP('what-is-oob-cap-value'); ?></span><br />
                &nbsp; &nbsp; <?php echo $pf->getHtmlForNamedElementFull('oob_cap_value', array('style' => 'width: 80px;')); ?>
            </p>

            <p> &nbsp; &nbsp; <span>Cap Type <?php Helper_Tooltip::toolTipFromWP('what-is-oob-cap-type'); ?></span><br />
                <?php echo $pf->getHtmlForNamedElementFull('oob_cap_type'); ?>
            </p>

            <div id="span-success-url">
                <p style="clear: both;"><span>Success URL <?php Helper_Tooltip::toolTipFromWP('what-is-the-success-url'); ?></span><br>
                    <?php echo $pf->getHtmlForNamedElementFull('success_url', array('class' => 'full-width', 'id' => 'success-url')); ?>
                </p>

                <p><span>Failure URL <?php Helper_Tooltip::toolTipFromWP('what-is-the-failure-url'); ?></span><br>
                    <?php echo $pf->getHtmlForNamedElementFull('failure_url', array('class' => 'full-width', 'id' => 'failure-url')); ?>
                </p>
            </div>

            <div class="clear"></div>

        </div><!--rightinfo-->

        <div class="clear"></div>
    </div><!--setup-->

</div><!--settings-->

<?php
echo '<div class="settings">';
?>

<h3><span id="toggle-advanced-h3" style="cursor: pointer;"> Advanced Settings </span><span class="opened"><a id="advanced-settings-toggle-link" href="#"><img src="/images/closed.png"/></a></span></h3>

<div class="options" id="advanced-settings-div">

    <div class="top">
        <p><span>Partners Per <?php Helper_Tooltip::toolTipFromWP('what-is-leads-per'); ?></span><br />
            <?php echo $pf->getHtmlForNamedElementFull('leads_per', array('id' => 'leads-per')); ?>
        </p>

        <p><span>Distribution <?php Helper_Tooltip::toolTipFromWP('what-is-campaign-distribution'); ?></span><br />
            <?php echo $pf->getHtmlForNamedElementFull('distribution'); ?>
        </p>

        <span id="repost-div">
            <p><span>Repost <?php Helper_Tooltip::toolTipFromWP('what-is-the-repost-toggle'); ?></span><br />
                <?php echo $pf->getHtmlForNamedElementFull('should_repost'); ?>
            </p>

            <span id="repost-div-setting">
                <p><span>Every (hours) <?php Helper_Tooltip::toolTipFromWP('what-is-repost-every-hours'); ?></span><br />
                    <?php echo $pf->getHtmlForNamedElementFull('repost_hours'); ?>
                </p>

                <p><span>Maximum <?php Helper_Tooltip::toolTipFromWP('what-is-repost-maximum'); ?></span><br />
                    <?php echo $pf->getHtmlForNamedElementFull('repost_max'); ?>
                </p>
            </span>
        </span>
        <div class="clear"></div>
    </div><!--top-->
    
    <div class="top">
        <span id="ping-post-setting">
            <p><span>Bid Response <?php Helper_Tooltip::toolTipFromWP('what-is-bid-response'); ?></span><br />
                <?php echo $pf->getHtmlForNamedElementFull('bid_response_type'); ?>
            </p>

            <p><span>&nbsp;</span><br />
                <span id="bid-response-value-prefix">%</span>
                <?php echo $pf->getHtmlForNamedElementFull('bid_response_value'); ?>
            </p>
        </span>
        
        <p style="width:150px;"><span>Campaign Timeout <?php Helper_Tooltip::toolTipFromWP('what-is-campaign-timeout'); ?></span><br />
            <?php echo $pf->getHtmlForNamedElementFull('campaign_timeout'); ?>
        </p>
        
        <div class="clear"></div>
    </div>
    
    <div class="top">
        
        <p><span>Response <?php Helper_Tooltip::toolTipFromWP('what-is-response-type'); ?></span><br />
            <?php echo $pf->getHtmlForNamedElementFull('response_type'); ?>
        </p>
        
            <p><span>Delivery <?php Helper_Tooltip::toolTipFromWP('what-is-delivery-type'); ?></span><br />
                <?php echo $pf->getHtmlForNamedElementFull('delivery_type'); ?>
            </p>

            <div id="oob-throttle-settings" class="top">
                <p><span>Throttle <?php Helper_Tooltip::toolTipFromWP('what-is-oob-throttle-value'); ?></span><br />
                    <?php echo $pf->getHtmlForNamedElementFull('throttle_value', array('style' => 'width: 80px;')); ?>
                </p>

                <p style="width: 150px;"><span>Throttle Type <?php Helper_Tooltip::toolTipFromWP('what-is-oob-throttle-type'); ?></span><br />
                    <?php echo $pf->getHtmlForNamedElementFull('throttle_type'); ?>
                </p>
            </div><!--top-->

        <div class="clear"></div>
    </div>
    <div class="bottom">
        <p><span>Maximum delivery retries per partner <?php Helper_Tooltip::toolTipFromWP('what-is-maximum-delivery-retries-per-partner'); ?></span>
            <?php echo $pf->getHtmlForNamedElementFull('partner_retries', array('id' => 'partner-retries')); ?> <span>(maximum 5)</span>
        </p>

        <p class="last"><label><?php echo $pf->getHtmlForNamedElementFull('capalp'); ?> <span>Count 'Always' delivery partners against 'Partners Per' <?php Helper_Tooltip::toolTipFromWP('count-always-yes-partners-against-leads-per'); ?></span></label></p>
        <p class="last" id="label-append-succ-url"><label><?php echo $pf->getHtmlForNamedElementFull('append_succ_url'); ?> <span>Append all partner success URLs to final campaign success url <?php Helper_Tooltip::toolTipFromWP('append-success-url-to-campaign-success-url'); ?></span></label></p>
        <?php if ($showIndustryId) { ?>
            <p><span>Industry</span> <?php echo $pf->getHtmlForNamedElementFull('industry_id'); ?></p>
        <?php } ?>

    </div><!--bottom-->

    <div class="clear"></div>
</div><!--options-->

<script type="text/javascript">

    $(document).ready(function() {
        shouldRepostChanged();
        campaignTypeChanged();


        $('#should-repost').click(shouldRepostChanged);
        $('#should-repost').change(shouldRepostChanged);

        $('#campaign-type').click(campaignTypeChanged);
        $('#campaign-type').change(campaignTypeChanged);
        $('#bid-response-type').change(bidResponseTypeChanged);

        $('#advanced-settings-toggle-link').click(toggleAdvanced);
        $('#toggle-advanced-h3').click(toggleAdvanced);

        $('#success-url, #failure-url').blur(function() {
            var v = $(this).val();
            if (v && v.indexOf('://') == -1) {
                $(this).val('http://' + v);
            }
        });
        
        $('#response-type').change(function() {
            responseTypeSelectChanged();
        });
        
        $('#delivery-type').change(function() {
            deliveryTypeSelectChanged();
        });

        deliveryTypeSelectChanged();
        responseTypeSelectChanged();

        $('#throttle-value').keyup(throttleValueChanged);
        $('#throttle-value').change(throttleValueChanged);
        throttleValueChanged();

        $('#oob-cap-value').keyup(oobCapValueChanged);
        $('#oob-cap-value').change(oobCapValueChanged);
        oobCapValueChanged();
    <?php
        $err = $pf->getForm()->getAllErrors();
        if (
                !empty($err['repost_hours']) || 
                !empty($err['repost_max']) || 
                !empty($err['leads_per']) || 
                !empty($err['partner_retries']) ||
                !empty($autoExpandAdvance)
            ) {
    ?>

            $('#advanced-settings-div').show();
            $('#advanced-settings-toggle-link').html('<img src="/images/opened.png"/>');

    <?php
        }
        Helper_Tooltip::jscript();
    ?>
            
    });

    function campaignTypeChanged() {
        if ($('#campaign-type').val() == '2') {
            // If it is "Master" type hide reposting controls
            $('#repost-div').hide();
        } else {
            // Otherwise show them
            $('#repost-div').show();
        }

        if ($('#campaign-type').val() == 3) {
            // show "Auction" in Distribution if campaign type = "Ping + Post" or "Ping / Post"
            $("#campaign-distribution option").show();
        } else if ($('#campaign-type').val() == 4) {
            $("#campaign-distribution option[value='2']").show().siblings().hide();
            $("#campaign-distribution").val('2');
        } else {
            // Otherwies hide it & assign default value if it was "Auction"
            $("#campaign-distribution option[value='2']").hide().siblings().show();
            if ($("#campaign-distribution").val() == '2') {
                $("#campaign-distribution").val('0');
            }
        }
        
        // show-hide bid-response
        if ($('#campaign-type').val() == 4) {
            $('#ping-post-setting').show();
            bidResponseTypeChanged();
        } else {
            $('#ping-post-setting').hide();
        }
    }
    ;
    
    function bidResponseTypeChanged() {
        if ($('#bid-response-type').val() === '1') {
            $('#bid-response-value-prefix').text('%');
        } else {
            $('#bid-response-value-prefix').text('$');
        }
    }

    function toggleAdvanced(e) {
        e.preventDefault();
        var v = $('#advanced-settings-div');
        v.toggle();
        if (v.is(':visible')) {
            $('#advanced-settings-toggle-link').html('<img src="/images/opened.png"/>');
        } else {
            $('#advanced-settings-toggle-link').html('<img src="/images/closed.png"/>');
        }
    }
    ;

    function shouldRepostChanged() {
        var v = parseInt($('#should-repost').val());
        if (v == 0) {
            $('#repost-hours-div, #repost-max-div').addClass('disabledDiv');
            $('#repost-hours, #repost-max').attr('disabled', 'disabled');
            $('#repost-div-setting').hide();
        } else {
            $('#repost-hours-div, #repost-max-div').removeClass('disabledDiv');
            $('#repost-hours, #repost-max').removeAttr('disabled');
            $('#repost-div-setting').show();
        }
    }
    ;

    function deliveryTypeSelectChanged() {
        if ($('#delivery-type').val() == '2') {
            $('#oob-throttle-settings').show();
            $('#label-append-succ-url').hide();
        } else {
            $('#oob-throttle-settings').hide();
            if ($('#response-type').val() == '1') {
                $('#label-append-succ-url').show();
            }
        }
    }
    ;

    function responseTypeSelectChanged() {
        if ($('#response-type').val() == '2') {
            $('#span-success-url').hide();
            $('#label-append-succ-url').hide();
        } else {
            $('#span-success-url').show();
            if ($('#delivery-type').val() == '1') {
                $('#label-append-succ-url').show();
            }
        }
    }
    ;

    function throttleValueChanged() {
        var v = $('#throttle-value').val();
        if (v == '0') {
            $('#throttle-type').attr('disabled', 'disabled');
        } else {
            $('#throttle-type').removeAttr('disabled');
        }
    }
    ;

    function oobCapValueChanged() {
        var v = $('#oob-cap-value').val();
        if (v == '0') {
            $('#oob-cap-type').attr('disabled', 'disabled');
        } else {
            $('#oob-cap-type').removeAttr('disabled');
        }
    }

</script>
