<?php

return array (
  'C00-P01' => 
  array (
    'partner' => 
    array (
      'id' => '1',
      'user_id' => '2',
      'created_at' => '2013-02-11 15:58:02',
      'wrapped_campaign_id' => NULL,
      'name' => 'C00-P01',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => 'x',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      2308 => 
      array (
        0 => '2308',
        'id' => '2308',
        1 => '1',
        'partner_id' => '1',
        2 => 'sys_country',
        'name' => 'sys_country',
        3 => '[:country_code_3chars:]',
        'value' => '[:country_code_3chars:]',
        4 => NULL,
        'modifier' => NULL,
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C00-P02' => 
  array (
    'partner' => 
    array (
      'id' => '2',
      'user_id' => '2',
      'created_at' => '2013-02-11 18:04:50',
      'wrapped_campaign_id' => NULL,
      'name' => 'C00-P02',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '|',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0.12',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      2300 => 
      array (
        0 => '2300',
        'id' => '2300',
        1 => '2',
        'partner_id' => '2',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => NULL,
        'modifier' => NULL,
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C00-P03' => 
  array (
    'partner' => 
    array (
      'id' => '3',
      'user_id' => '2',
      'created_at' => '2013-02-11 18:05:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C00-P03',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => 'x',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      2298 => 
      array (
        0 => '2298',
        'id' => '2298',
        1 => '3',
        'partner_id' => '3',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => NULL,
        'modifier' => NULL,
      ),
    ),
    'filters' => 
    array (
      29 => 
      array (
        0 => '29',
        'id' => '29',
        1 => '3',
        'partner_id' => '3',
        2 => '1',
        'is_active' => '1',
        3 => '2',
        'filter_action' => '2',
        4 => '2',
        'field_type_id' => '2',
        5 => '',
        'system_field' => '',
        6 => '-1',
        'match_type' => '-1',
        7 => '@@',
        'match_value' => '@@',
        8 => 'http://www.changed.com/',
        'argument' => 'http://www.changed.com/',
      ),
    ),
    'settings' => 
    array (
    ),
  ),
  'C01-P1' => 
  array (
    'partner' => 
    array (
      'id' => '4',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C01-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => 'x',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      129 => 
      array (
        0 => '129',
        'id' => '129',
        1 => '4',
        'partner_id' => '4',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C01-P2' => 
  array (
    'partner' => 
    array (
      'id' => '5',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C01-P2',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'Fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      130 => 
      array (
        0 => '130',
        'id' => '130',
        1 => '5',
        'partner_id' => '5',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C01-P3' => 
  array (
    'partner' => 
    array (
      'id' => '6',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C01-P3',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'Fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '|',
      'success_url' => '$23',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      131 => 
      array (
        0 => '131',
        'id' => '131',
        1 => '6',
        'partner_id' => '6',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C02-P1' => 
  array (
    'partner' => 
    array (
      'id' => '7',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C02-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'Fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
      30 => 
      array (
        0 => '30',
        'id' => '30',
        1 => '7',
        'partner_id' => '7',
        2 => '1',
        'is_active' => '1',
        3 => '1',
        'filter_action' => '1',
        4 => NULL,
        'field_type_id' => NULL,
        5 => ':ip_address:',
        'system_field' => ':ip_address:',
        6 => '-1',
        'match_type' => '-1',
        7 => 'bee',
        'match_value' => 'bee',
        8 => '',
        'argument' => '',
      ),
    ),
    'settings' => 
    array (
      132 => 
      array (
        0 => '132',
        'id' => '132',
        1 => '7',
        'partner_id' => '7',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C03-P1' => 
  array (
    'partner' => 
    array (
      'id' => '8',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C03-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'Fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      593 => 
      array (
        0 => '593',
        'id' => '593',
        1 => '8',
        'partner_id' => '8',
        2 => 'state',
        'name' => 'state',
        3 => '[:state_or_region:]',
        'value' => '[:state_or_region:]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      133 => 
      array (
        0 => '133',
        'id' => '133',
        1 => '8',
        'partner_id' => '8',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C04-P1' => 
  array (
    'partner' => 
    array (
      'id' => '9',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C04-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'OK',
      'failure_keyword' => 'Fail',
      'delivery_addr' => 'http://w1.localhost/return-url.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '\\n',
      'success_url' => '',
      'price_per_lead' => '1',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      594 => 
      array (
        0 => '594',
        'id' => '594',
        1 => '9',
        'partner_id' => '9',
        2 => 'e',
        'name' => 'e',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      134 => 
      array (
        0 => '134',
        'id' => '134',
        1 => '9',
        'partner_id' => '9',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C05-P1' => 
  array (
    'partner' => 
    array (
      'id' => '10',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C05-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'OK',
      'failure_keyword' => 'Fail',
      'delivery_addr' => 'http://w1.localhost/return-url.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '\\n',
      'success_url' => '',
      'price_per_lead' => '1',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      595 => 
      array (
        0 => '595',
        'id' => '595',
        1 => '10',
        'partner_id' => '10',
        2 => 'e[][]',
        'name' => 'e[][]',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => 'dlg-modifier-replacements
First_Name
1
joe
%2B%5B%3Aip_address%3A%5D%2B%5B%3Astate_or_region%3A%5D%2B%40',
        'modifier' => 'dlg-modifier-replacements
First_Name
1
joe
%2B%5B%3Aip_address%3A%5D%2B%5B%3Astate_or_region%3A%5D%2B%40',
      ),
      596 => 
      array (
        0 => '596',
        'id' => '596',
        1 => '10',
        'partner_id' => '10',
        2 => 'i',
        'name' => 'i',
        3 => '+[:ip_address:]+',
        'value' => '+[:ip_address:]+',
        4 => '',
        'modifier' => '',
      ),
      597 => 
      array (
        0 => '597',
        'id' => '597',
        1 => '10',
        'partner_id' => '10',
        2 => 'mod2_1',
        'name' => 'mod2_1',
        3 => '[Other_1]',
        'value' => '[Other_1]',
        4 => 'dlg-modifier-replacements
Other_1
1
a
b
1
b
a',
        'modifier' => 'dlg-modifier-replacements
Other_1
1
a
b
1
b
a',
      ),
      598 => 
      array (
        0 => '598',
        'id' => '598',
        1 => '10',
        'partner_id' => '10',
        2 => 'mod2_2',
        'name' => 'mod2_2',
        3 => '[Other_2]',
        'value' => '[Other_2]',
        4 => 'dlg-modifier-replacements
Other_2
1
a
b
1
b
a',
        'modifier' => 'dlg-modifier-replacements
Other_2
1
a
b
1
b
a',
      ),
      599 => 
      array (
        0 => '599',
        'id' => '599',
        1 => '10',
        'partner_id' => '10',
        2 => 'test_blank',
        'name' => 'test_blank',
        3 => '[Address_Line1]',
        'value' => '[Address_Line1]',
        4 => 'dlg-modifier-replacements
Address_Line1
1

it%20was%20blank',
        'modifier' => 'dlg-modifier-replacements
Address_Line1
1

it%20was%20blank',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      135 => 
      array (
        0 => '135',
        'id' => '135',
        1 => '10',
        'partner_id' => '10',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C06-P1' => 
  array (
    'partner' => 
    array (
      'id' => '11',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C06-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      600 => 
      array (
        0 => '600',
        'id' => '600',
        1 => '11',
        'partner_id' => '11',
        2 => 'byr',
        'name' => 'byr',
        3 => '[:birth_year:]',
        'value' => '[:birth_year:]',
        4 => '',
        'modifier' => '',
      ),
      601 => 
      array (
        0 => '601',
        'id' => '601',
        1 => '11',
        'partner_id' => '11',
        2 => 'cc3',
        'name' => 'cc3',
        3 => '[:country_code_3chars:]',
        'value' => '[:country_code_3chars:]',
        4 => '',
        'modifier' => '',
      ),
      602 => 
      array (
        0 => '602',
        'id' => '602',
        1 => '11',
        'partner_id' => '11',
        2 => 'rapleaf_gender',
        'name' => 'rapleaf_gender',
        3 => '[:gender:]',
        'value' => '[:gender:]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      136 => 
      array (
        0 => '136',
        'id' => '136',
        1 => '11',
        'partner_id' => '11',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C07-P1' => 
  array (
    'partner' => 
    array (
      'id' => '12',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C07-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      603 => 
      array (
        0 => '603',
        'id' => '603',
        1 => '12',
        'partner_id' => '12',
        2 => 'rapleaf_age',
        'name' => 'rapleaf_age',
        3 => '[:age:]',
        'value' => '[:age:]',
        4 => '',
        'modifier' => '',
      ),
      604 => 
      array (
        0 => '604',
        'id' => '604',
        1 => '12',
        'partner_id' => '12',
        2 => 'rapleaf_gender',
        'name' => 'rapleaf_gender',
        3 => '[:gender:]',
        'value' => '[:gender:]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      137 => 
      array (
        0 => '137',
        'id' => '137',
        1 => '12',
        'partner_id' => '12',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C08-P1' => 
  array (
    'partner' => 
    array (
      'id' => '13',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C08-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      605 => 
      array (
        0 => '605',
        'id' => '605',
        1 => '13',
        'partner_id' => '13',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
      31 => 
      array (
        0 => '31',
        'id' => '31',
        1 => '13',
        'partner_id' => '13',
        2 => '1',
        'is_active' => '1',
        3 => '1',
        'filter_action' => '1',
        4 => NULL,
        'field_type_id' => NULL,
        5 => ':country_code:',
        'system_field' => ':country_code:',
        6 => '-1',
        'match_type' => '-1',
        7 => 'US|GB|UK|DE',
        'match_value' => 'US|GB|UK|DE',
        8 => '',
        'argument' => '',
      ),
      32 => 
      array (
        0 => '32',
        'id' => '32',
        1 => '13',
        'partner_id' => '13',
        2 => '1',
        'is_active' => '1',
        3 => '1',
        'filter_action' => '1',
        4 => '21',
        'field_type_id' => '21',
        5 => '',
        'system_field' => '',
        6 => '-1',
        'match_type' => '-1',
        7 => 'US|GB|UK|DE',
        'match_value' => 'US|GB|UK|DE',
        8 => '',
        'argument' => '',
      ),
    ),
    'settings' => 
    array (
      138 => 
      array (
        0 => '138',
        'id' => '138',
        1 => '13',
        'partner_id' => '13',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C09-P1' => 
  array (
    'partner' => 
    array (
      'id' => '14',
      'user_id' => '2',
      'created_at' => '0000-00-00 00:00:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'C09-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      606 => 
      array (
        0 => '606',
        'id' => '606',
        1 => '14',
        'partner_id' => '14',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      607 => 
      array (
        0 => '607',
        'id' => '607',
        1 => '14',
        'partner_id' => '14',
        2 => 'sd',
        'name' => 'sd',
        3 => '[:submit_date:]',
        'value' => '[:submit_date:]',
        4 => '',
        'modifier' => '',
      ),
      608 => 
      array (
        0 => '608',
        'id' => '608',
        1 => '14',
        'partner_id' => '14',
        2 => 'st',
        'name' => 'st',
        3 => '[:submit_time:]',
        'value' => '[:submit_time:]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      139 => 
      array (
        0 => '139',
        'id' => '139',
        1 => '14',
        'partner_id' => '14',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C10-P1' => 
  array (
    'partner' => 
    array (
      'id' => '15',
      'user_id' => '2',
      'created_at' => '2012-03-07 22:26:14',
      'wrapped_campaign_id' => NULL,
      'name' => 'C10-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '2',
      'delivery_ctype' => '4',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      609 => 
      array (
        0 => '609',
        'id' => '609',
        1 => '15',
        'partner_id' => '15',
        2 => 'e',
        'name' => 'e',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      140 => 
      array (
        0 => '140',
        'id' => '140',
        1 => '15',
        'partner_id' => '15',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P01' => 
  array (
    'partner' => 
    array (
      'id' => '16',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P01',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '0',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'username taken',
      'template' => NULL,
    ),
    'fields' => 
    array (
      610 => 
      array (
        0 => '610',
        'id' => '610',
        1 => '16',
        'partner_id' => '16',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      141 => 
      array (
        0 => '141',
        'id' => '141',
        1 => '16',
        'partner_id' => '16',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P02' => 
  array (
    'partner' => 
    array (
      'id' => '17',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P02',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      611 => 
      array (
        0 => '611',
        'id' => '611',
        1 => '17',
        'partner_id' => '17',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      142 => 
      array (
        0 => '142',
        'id' => '142',
        1 => '17',
        'partner_id' => '17',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P03' => 
  array (
    'partner' => 
    array (
      'id' => '18',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P03',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      612 => 
      array (
        0 => '612',
        'id' => '612',
        1 => '18',
        'partner_id' => '18',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      143 => 
      array (
        0 => '143',
        'id' => '143',
        1 => '18',
        'partner_id' => '18',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P04' => 
  array (
    'partner' => 
    array (
      'id' => '19',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P04',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      613 => 
      array (
        0 => '613',
        'id' => '613',
        1 => '19',
        'partner_id' => '19',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      144 => 
      array (
        0 => '144',
        'id' => '144',
        1 => '19',
        'partner_id' => '19',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P05' => 
  array (
    'partner' => 
    array (
      'id' => '20',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P05',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      614 => 
      array (
        0 => '614',
        'id' => '614',
        1 => '20',
        'partner_id' => '20',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      145 => 
      array (
        0 => '145',
        'id' => '145',
        1 => '20',
        'partner_id' => '20',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P06' => 
  array (
    'partner' => 
    array (
      'id' => '21',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P06',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      615 => 
      array (
        0 => '615',
        'id' => '615',
        1 => '21',
        'partner_id' => '21',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      146 => 
      array (
        0 => '146',
        'id' => '146',
        1 => '21',
        'partner_id' => '21',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P07' => 
  array (
    'partner' => 
    array (
      'id' => '22',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P07',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      616 => 
      array (
        0 => '616',
        'id' => '616',
        1 => '22',
        'partner_id' => '22',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      147 => 
      array (
        0 => '147',
        'id' => '147',
        1 => '22',
        'partner_id' => '22',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P08' => 
  array (
    'partner' => 
    array (
      'id' => '23',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P08',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      617 => 
      array (
        0 => '617',
        'id' => '617',
        1 => '23',
        'partner_id' => '23',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      148 => 
      array (
        0 => '148',
        'id' => '148',
        1 => '23',
        'partner_id' => '23',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P09' => 
  array (
    'partner' => 
    array (
      'id' => '24',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P09',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      618 => 
      array (
        0 => '618',
        'id' => '618',
        1 => '24',
        'partner_id' => '24',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P10' => 
  array (
    'partner' => 
    array (
      'id' => '25',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P10',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'username taken',
      'template' => NULL,
    ),
    'fields' => 
    array (
      619 => 
      array (
        0 => '619',
        'id' => '619',
        1 => '25',
        'partner_id' => '25',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      149 => 
      array (
        0 => '149',
        'id' => '149',
        1 => '25',
        'partner_id' => '25',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P11' => 
  array (
    'partner' => 
    array (
      'id' => '26',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P11',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      620 => 
      array (
        0 => '620',
        'id' => '620',
        1 => '26',
        'partner_id' => '26',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P12' => 
  array (
    'partner' => 
    array (
      'id' => '27',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P12',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      621 => 
      array (
        0 => '621',
        'id' => '621',
        1 => '27',
        'partner_id' => '27',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P13' => 
  array (
    'partner' => 
    array (
      'id' => '28',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P13',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      622 => 
      array (
        0 => '622',
        'id' => '622',
        1 => '28',
        'partner_id' => '28',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P14' => 
  array (
    'partner' => 
    array (
      'id' => '29',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P14',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      623 => 
      array (
        0 => '623',
        'id' => '623',
        1 => '29',
        'partner_id' => '29',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P15' => 
  array (
    'partner' => 
    array (
      'id' => '30',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P15',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      624 => 
      array (
        0 => '624',
        'id' => '624',
        1 => '30',
        'partner_id' => '30',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P16' => 
  array (
    'partner' => 
    array (
      'id' => '31',
      'user_id' => '2',
      'created_at' => '2012-03-09 22:16:13',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P16',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      625 => 
      array (
        0 => '625',
        'id' => '625',
        1 => '31',
        'partner_id' => '31',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P17' => 
  array (
    'partner' => 
    array (
      'id' => '32',
      'user_id' => '2',
      'created_at' => '2012-05-03 23:56:38',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P17',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '2',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      626 => 
      array (
        0 => '626',
        'id' => '626',
        1 => '32',
        'partner_id' => '32',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      150 => 
      array (
        0 => '150',
        'id' => '150',
        1 => '32',
        'partner_id' => '32',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C11-P18' => 
  array (
    'partner' => 
    array (
      'id' => '33',
      'user_id' => '2',
      'created_at' => '2012-05-07 21:54:43',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P18',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '2',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      627 => 
      array (
        0 => '627',
        'id' => '627',
        1 => '33',
        'partner_id' => '33',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P19' => 
  array (
    'partner' => 
    array (
      'id' => '34',
      'user_id' => '2',
      'created_at' => '2012-05-08 01:38:09',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P19',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.locahlhost/succ11-o1',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'username taken',
      'template' => NULL,
    ),
    'fields' => 
    array (
      628 => 
      array (
        0 => '628',
        'id' => '628',
        1 => '34',
        'partner_id' => '34',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C11-P20' => 
  array (
    'partner' => 
    array (
      'id' => '35',
      'user_id' => '2',
      'created_at' => '2012-05-08 01:38:20',
      'wrapped_campaign_id' => NULL,
      'name' => 'C11-P20',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/succ.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.locahlhost/succ11-o2',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      629 => 
      array (
        0 => '629',
        'id' => '629',
        1 => '35',
        'partner_id' => '35',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C13-P1' => 
  array (
    'partner' => 
    array (
      'id' => '36',
      'user_id' => '2',
      'created_at' => '2012-03-19 21:14:07',
      'wrapped_campaign_id' => NULL,
      'name' => 'C13-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success',
      'failure_keyword' => '',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://wiki.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      151 => 
      array (
        0 => '151',
        'id' => '151',
        1 => '36',
        'partner_id' => '36',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C14-P1' => 
  array (
    'partner' => 
    array (
      'id' => '37',
      'user_id' => '2',
      'created_at' => '2012-03-20 21:10:38',
      'wrapped_campaign_id' => NULL,
      'name' => 'C14-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'success,0',
      'failure_keyword' => 'ERROR',
      'delivery_addr' => 'http://w1.localhost/?fail',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '|',
      'success_url' => '$2',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      152 => 
      array (
        0 => '152',
        'id' => '152',
        1 => '37',
        'partner_id' => '37',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C16-P1' => 
  array (
    'partner' => 
    array (
      'id' => '38',
      'user_id' => '2',
      'created_at' => '2012-05-08 00:01:42',
      'wrapped_campaign_id' => NULL,
      'name' => 'C16-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '5',
      'success_keyword' => 'success',
      'failure_keyword' => 'ERROR',
      'delivery_addr' => 'http://w1.localhost/xml.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '|',
      'success_url' => '$2',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => 'testing with %f1% and %f2%',
    ),
    'fields' => 
    array (
      630 => 
      array (
        0 => '630',
        'id' => '630',
        1 => '38',
        'partner_id' => '38',
        2 => 'f1',
        'name' => 'f1',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      631 => 
      array (
        0 => '631',
        'id' => '631',
        1 => '38',
        'partner_id' => '38',
        2 => 'f2',
        'name' => 'f2',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      153 => 
      array (
        0 => '153',
        'id' => '153',
        1 => '38',
        'partner_id' => '38',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C16-P2' => 
  array (
    'partner' => 
    array (
      'id' => '39',
      'user_id' => '2',
      'created_at' => '2013-03-06 18:30:02',
      'wrapped_campaign_id' => NULL,
      'name' => 'C16-P2',
      'create_from_tpl_id' => NULL,
      'posting_type' => '5',
      'success_keyword' => 'success',
      'failure_keyword' => 'ERROR',
      'delivery_addr' => 'http://w1.localhost/xml.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '|',
      'success_url' => '$2',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => '<value>%birthday_day%/%birthday_month%/%birthday_year%</value>',
    ),
    'fields' => 
    array (
      632 => 
      array (
        0 => '632',
        'id' => '632',
        1 => '39',
        'partner_id' => '39',
        2 => 'birthday_day',
        'name' => 'birthday_day',
        3 => '[Birthday_Day]',
        'value' => '[Birthday_Day]',
        4 => '',
        'modifier' => '',
      ),
      633 => 
      array (
        0 => '633',
        'id' => '633',
        1 => '39',
        'partner_id' => '39',
        2 => 'birthday_month',
        'name' => 'birthday_month',
        3 => '[Birthday_Month]',
        'value' => '[Birthday_Month]',
        4 => '',
        'modifier' => '',
      ),
      634 => 
      array (
        0 => '634',
        'id' => '634',
        1 => '39',
        'partner_id' => '39',
        2 => 'birthday_year',
        'name' => 'birthday_year',
        3 => '[Birthday_Year]',
        'value' => '[Birthday_Year]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C17-P1' => 
  array (
    'partner' => 
    array (
      'id' => '40',
      'user_id' => '2',
      'created_at' => '2012-05-31 00:44:51',
      'wrapped_campaign_id' => NULL,
      'name' => 'C17-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '4',
      'success_keyword' => 'OK',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/COREG/addTest.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://xxx.localhost/COREG/login?docket=[:aff_login_docket:]&ip_address=[:ip_address:]',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      635 => 
      array (
        0 => '635',
        'id' => '635',
        1 => '40',
        'partner_id' => '40',
        2 => 'birthday',
        'name' => 'birthday',
        3 => '01/01/[:birth_year:]',
        'value' => '01/01/[:birth_year:]',
        4 => '',
        'modifier' => '',
      ),
      636 => 
      array (
        0 => '636',
        'id' => '636',
        1 => '40',
        'partner_id' => '40',
        2 => 'city',
        'name' => 'city',
        3 => '[:city:]',
        'value' => '[:city:]',
        4 => 'dlg-modifier-replacements
:city:
1

Unknown',
        'modifier' => 'dlg-modifier-replacements
:city:
1

Unknown',
      ),
      637 => 
      array (
        0 => '637',
        'id' => '637',
        1 => '40',
        'partner_id' => '40',
        2 => 'country',
        'name' => 'country',
        3 => '[:country:]',
        'value' => '[:country:]',
        4 => 'dlg-modifier-replacements
:country:
1

United%20States',
        'modifier' => 'dlg-modifier-replacements
:country:
1

United%20States',
      ),
      638 => 
      array (
        0 => '638',
        'id' => '638',
        1 => '40',
        'partner_id' => '40',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      639 => 
      array (
        0 => '639',
        'id' => '639',
        1 => '40',
        'partner_id' => '40',
        2 => 'fname',
        'name' => 'fname',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
      640 => 
      array (
        0 => '640',
        'id' => '640',
        1 => '40',
        'partner_id' => '40',
        2 => 'ip_address',
        'name' => 'ip_address',
        3 => '[:ip_address:]',
        'value' => '[:ip_address:]',
        4 => '',
        'modifier' => '',
      ),
      641 => 
      array (
        0 => '641',
        'id' => '641',
        1 => '40',
        'partner_id' => '40',
        2 => 'lname',
        'name' => 'lname',
        3 => '[Last_Name]',
        'value' => '[Last_Name]',
        4 => '',
        'modifier' => '',
      ),
      642 => 
      array (
        0 => '642',
        'id' => '642',
        1 => '40',
        'partner_id' => '40',
        2 => 'looking_for_desc',
        'name' => 'looking_for_desc',
        3 => 'Erotic Chat/Email/Phone Fantasies, 1-on-1 sex, Discreet Relationship',
        'value' => 'Erotic Chat/Email/Phone Fantasies, 1-on-1 sex, Discreet Relationship',
        4 => '',
        'modifier' => '',
      ),
      643 => 
      array (
        0 => '643',
        'id' => '643',
        1 => '40',
        'partner_id' => '40',
        2 => 'looking_for_person',
        'name' => 'looking_for_person',
        3 => '[Other_1]',
        'value' => '[Other_1]',
        4 => '',
        'modifier' => '',
      ),
      644 => 
      array (
        0 => '644',
        'id' => '644',
        1 => '40',
        'partner_id' => '40',
        2 => 'password',
        'name' => 'password',
        3 => '[Password]',
        'value' => '[Password]',
        4 => '',
        'modifier' => '',
      ),
      645 => 
      array (
        0 => '645',
        'id' => '645',
        1 => '40',
        'partner_id' => '40',
        2 => 'profile',
        'name' => 'profile',
        3 => 'Please change me!',
        'value' => 'Please change me!',
        4 => '',
        'modifier' => '',
      ),
      646 => 
      array (
        0 => '646',
        'id' => '646',
        1 => '40',
        'partner_id' => '40',
        2 => 'sex',
        'name' => 'sex',
        3 => '[Gender]',
        'value' => '[Gender]',
        4 => '',
        'modifier' => '',
      ),
      647 => 
      array (
        0 => '647',
        'id' => '647',
        1 => '40',
        'partner_id' => '40',
        2 => 'state',
        'name' => 'state',
        3 => '[:state_or_region:]',
        'value' => '[:state_or_region:]',
        4 => 'dlg-modifier-replacements
:state_or_region:
1

Unknown',
        'modifier' => 'dlg-modifier-replacements
:state_or_region:
1

Unknown',
      ),
      648 => 
      array (
        0 => '648',
        'id' => '648',
        1 => '40',
        'partner_id' => '40',
        2 => 'state_code',
        'name' => 'state_code',
        3 => '[:state_or_region_code:]',
        'value' => '[:state_or_region_code:]',
        4 => 'dlg-modifier-replacements
:state_or_region_code:
1

Unknown%20State%20Code',
        'modifier' => 'dlg-modifier-replacements
:state_or_region_code:
1

Unknown%20State%20Code',
      ),
      649 => 
      array (
        0 => '649',
        'id' => '649',
        1 => '40',
        'partner_id' => '40',
        2 => 'subpid',
        'name' => 'subpid',
        3 => '[Campaign]',
        'value' => '[Campaign]',
        4 => '',
        'modifier' => '',
      ),
      650 => 
      array (
        0 => '650',
        'id' => '650',
        1 => '40',
        'partner_id' => '40',
        2 => 'title',
        'name' => 'title',
        3 => 'Please change me!',
        'value' => 'Please change me!',
        4 => '',
        'modifier' => '',
      ),
      651 => 
      array (
        0 => '651',
        'id' => '651',
        1 => '40',
        'partner_id' => '40',
        2 => 'uname',
        'name' => 'uname',
        3 => '[Username]',
        'value' => '[Username]',
        4 => '',
        'modifier' => '',
      ),
      652 => 
      array (
        0 => '652',
        'id' => '652',
        1 => '40',
        'partner_id' => '40',
        2 => 'zip',
        'name' => 'zip',
        3 => '[Postal_Code]',
        'value' => '[Postal_Code]',
        4 => 'dlg-modifier-replacements
Postal_Code
1

00000',
        'modifier' => 'dlg-modifier-replacements
Postal_Code
1

00000',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      154 => 
      array (
        0 => '154',
        'id' => '154',
        1 => '40',
        'partner_id' => '40',
        2 => '1',
        'key' => '1',
        3 => '42=j5r#L@FsxOc\'GP9-kZaCHmEgu1B7w:UqoDVb8.Y&X!f,I3T?p_y W6/J$Mn*Q^%Ktdz+;NSlev0|ARi"h',
        'value' => '42=j5r#L@FsxOc\'GP9-kZaCHmEgu1B7w:UqoDVb8.Y&X!f,I3T?p_y W6/J$Mn*Q^%Ktdz+;NSlev0|ARi"h',
      ),
    ),
  ),
  'C19-P1' => 
  array (
    'partner' => 
    array (
      'id' => '41',
      'user_id' => '2',
      'created_at' => '2012-06-25 16:43:26',
      'wrapped_campaign_id' => NULL,
      'name' => 'C19-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      653 => 
      array (
        0 => '653',
        'id' => '653',
        1 => '41',
        'partner_id' => '41',
        2 => 'strlen2',
        'name' => 'strlen2',
        3 => '[Username]',
        'value' => '[Username]',
        4 => 'dlg-modifier-replacements
Username
-7
9
bla-bla-bla',
        'modifier' => 'dlg-modifier-replacements
Username
-7
9
bla-bla-bla',
      ),
      654 => 
      array (
        0 => '654',
        'id' => '654',
        1 => '41',
        'partner_id' => '41',
        2 => 'test_strlen',
        'name' => 'test_strlen',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
      33 => 
      array (
        0 => '33',
        'id' => '33',
        1 => '41',
        'partner_id' => '41',
        2 => '1',
        'is_active' => '1',
        3 => '1',
        'filter_action' => '1',
        4 => '7',
        'field_type_id' => '7',
        5 => '',
        'system_field' => '',
        6 => '-7',
        'match_type' => '-7',
        7 => '9',
        'match_value' => '9',
        8 => '',
        'argument' => '',
      ),
    ),
    'settings' => 
    array (
      155 => 
      array (
        0 => '155',
        'id' => '155',
        1 => '41',
        'partner_id' => '41',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C20-P1' => 
  array (
    'partner' => 
    array (
      'id' => '42',
      'user_id' => '2',
      'created_at' => '2012-06-25 20:30:32',
      'wrapped_campaign_id' => NULL,
      'name' => 'C20-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      655 => 
      array (
        0 => '655',
        'id' => '655',
        1 => '42',
        'partner_id' => '42',
        2 => 'test_zipcode',
        'name' => 'test_zipcode',
        3 => '[:postal_code:]',
        'value' => '[:postal_code:]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C21-P1' => 
  array (
    'partner' => 
    array (
      'id' => '43',
      'user_id' => '2',
      'created_at' => '2012-07-03 21:01:18',
      'wrapped_campaign_id' => NULL,
      'name' => 'C21-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      656 => 
      array (
        0 => '656',
        'id' => '656',
        1 => '43',
        'partner_id' => '43',
        2 => 'ipadd_out',
        'name' => 'ipadd_out',
        3 => '[:ip_address:]',
        'value' => '[:ip_address:]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C23-P1' => 
  array (
    'partner' => 
    array (
      'id' => '44',
      'user_id' => '2',
      'created_at' => '2012-07-23 00:37:21',
      'wrapped_campaign_id' => NULL,
      'name' => 'C23-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      657 => 
      array (
        0 => '657',
        'id' => '657',
        1 => '44',
        'partner_id' => '44',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      658 => 
      array (
        0 => '658',
        'id' => '658',
        1 => '44',
        'partner_id' => '44',
        2 => 'pc_test',
        'name' => 'pc_test',
        3 => '[:postal_code:]',
        'value' => '[:postal_code:]',
        4 => '',
        'modifier' => '',
      ),
      659 => 
      array (
        0 => '659',
        'id' => '659',
        1 => '44',
        'partner_id' => '44',
        2 => 'zip_orig',
        'name' => 'zip_orig',
        3 => '[Postal_Code]',
        'value' => '[Postal_Code]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C24-P1' => 
  array (
    'partner' => 
    array (
      'id' => '45',
      'user_id' => '2',
      'created_at' => '2012-07-31 15:47:11',
      'wrapped_campaign_id' => NULL,
      'name' => 'C24-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      660 => 
      array (
        0 => '660',
        'id' => '660',
        1 => '45',
        'partner_id' => '45',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      661 => 
      array (
        0 => '661',
        'id' => '661',
        1 => '45',
        'partner_id' => '45',
        2 => 'ip',
        'name' => 'ip',
        3 => '[IP_Address]',
        'value' => '[IP_Address]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C25-P1' => 
  array (
    'partner' => 
    array (
      'id' => '46',
      'user_id' => '2',
      'created_at' => '2012-11-05 21:46:21',
      'wrapped_campaign_id' => NULL,
      'name' => 'C25-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '1',
      'username_failed_keyword' => 'SUGGESTIONS:',
      'template' => NULL,
    ),
    'fields' => 
    array (
      662 => 
      array (
        0 => '662',
        'id' => '662',
        1 => '46',
        'partner_id' => '46',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      663 => 
      array (
        0 => '663',
        'id' => '663',
        1 => '46',
        'partner_id' => '46',
        2 => 'ip',
        'name' => 'ip',
        3 => '[IP_Address]',
        'value' => '[IP_Address]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C29-P1' => 
  array (
    'partner' => 
    array (
      'id' => '47',
      'user_id' => '2',
      'created_at' => '2013-01-09 22:32:37',
      'wrapped_campaign_id' => NULL,
      'name' => 'C29-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'succ',
      'failure_keyword' => '',
      'delivery_addr' => 'http://w1.localhost/?mail=[Email]&ip=[:ip_address:]',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      156 => 
      array (
        0 => '156',
        'id' => '156',
        1 => '47',
        'partner_id' => '47',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C30-P1' => 
  array (
    'partner' => 
    array (
      'id' => '48',
      'user_id' => '2',
      'created_at' => '2013-01-09 22:48:51',
      'wrapped_campaign_id' => NULL,
      'name' => 'C30-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'succ',
      'failure_keyword' => '',
      'delivery_addr' => 'http://w1.localhost/?mail=[Email]&ip=[:ip_address:]&x=[xxx]',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      157 => 
      array (
        0 => '157',
        'id' => '157',
        1 => '48',
        'partner_id' => '48',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C34-P1' => 
  array (
    'partner' => 
    array (
      'id' => '49',
      'user_id' => '2',
      'created_at' => '2013-01-18 22:38:18',
      'wrapped_campaign_id' => NULL,
      'name' => 'C34-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '2',
      'success_keyword' => 'success',
      'failure_keyword' => 'FAIL:',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => 'x',
      'success_url' => 'http://w1.localhost/',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'C35-P1' => 
  array (
    'partner' => 
    array (
      'id' => '50',
      'user_id' => '2',
      'created_at' => '2013-03-06 16:26:21',
      'wrapped_campaign_id' => NULL,
      'name' => 'C35-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '6',
      'success_keyword' => 'success',
      'failure_keyword' => 'ERROR',
      'delivery_addr' => 'http://w1.localhost/xml.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '|',
      'success_url' => '$2',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => 'testing with "%f1% %f2%"',
    ),
    'fields' => 
    array (
      664 => 
      array (
        0 => '664',
        'id' => '664',
        1 => '50',
        'partner_id' => '50',
        2 => 'f1',
        'name' => 'f1',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      665 => 
      array (
        0 => '665',
        'id' => '665',
        1 => '50',
        'partner_id' => '50',
        2 => 'f2',
        'name' => 'f2',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      158 => 
      array (
        0 => '158',
        'id' => '158',
        1 => '50',
        'partner_id' => '50',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'C36-P1' => 
  array (
    'partner' => 
    array (
      'id' => '55',
      'user_id' => '2',
      'created_at' => '2013-03-07 22:00:50',
      'wrapped_campaign_id' => NULL,
      'name' => 'C36-P1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '6',
      'success_keyword' => 'success',
      'failure_keyword' => 'ERROR',
      'delivery_addr' => 'http://w1.localhost/xml.php',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '1',
      'delimiter' => '|',
      'success_url' => '$2',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => 'testing with "%f1% %f2%"',
    ),
    'fields' => 
    array (
      1188 => 
      array (
        0 => '1188',
        'id' => '1188',
        1 => '55',
        'partner_id' => '55',
        2 => 'age',
        'name' => 'age',
        3 => '[Age]',
        'value' => '[Age]',
        4 => '',
        'modifier' => '',
      ),
      1187 => 
      array (
        0 => '1187',
        'id' => '1187',
        1 => '55',
        'partner_id' => '55',
        2 => 'age_sys',
        'name' => 'age_sys',
        3 => '[:age:]',
        'value' => '[:age:]',
        4 => '',
        'modifier' => '',
      ),
      1186 => 
      array (
        0 => '1186',
        'id' => '1186',
        1 => '55',
        'partner_id' => '55',
        2 => 'email',
        'name' => 'email',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
  'Filtered Out 1' => 
  array (
    'partner' => 
    array (
      'id' => '51',
      'user_id' => '2',
      'created_at' => '2013-01-18 19:04:31',
      'wrapped_campaign_id' => NULL,
      'name' => 'Filtered Out 1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'succ',
      'failure_keyword' => '',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      666 => 
      array (
        0 => '666',
        'id' => '666',
        1 => '51',
        'partner_id' => '51',
        2 => 'fn',
        'name' => 'fn',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
      34 => 
      array (
        0 => '34',
        'id' => '34',
        1 => '51',
        'partner_id' => '51',
        2 => '1',
        'is_active' => '1',
        3 => '1',
        'filter_action' => '1',
        4 => '24',
        'field_type_id' => '24',
        5 => '',
        'system_field' => '',
        6 => '-1',
        'match_type' => '-1',
        7 => 'Jeronimo',
        'match_value' => 'Jeronimo',
        8 => '',
        'argument' => '',
      ),
    ),
    'settings' => 
    array (
      159 => 
      array (
        0 => '159',
        'id' => '159',
        1 => '51',
        'partner_id' => '51',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'Filtered Out 2' => 
  array (
    'partner' => 
    array (
      'id' => '52',
      'user_id' => '2',
      'created_at' => '2013-01-18 20:13:52',
      'wrapped_campaign_id' => NULL,
      'name' => 'Filtered Out 2',
      'create_from_tpl_id' => NULL,
      'posting_type' => '1',
      'success_keyword' => 'succ',
      'failure_keyword' => '',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
      667 => 
      array (
        0 => '667',
        'id' => '667',
        1 => '52',
        'partner_id' => '52',
        2 => 'fn',
        'name' => 'fn',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
      35 => 
      array (
        0 => '35',
        'id' => '35',
        1 => '52',
        'partner_id' => '52',
        2 => '1',
        'is_active' => '1',
        3 => '1',
        'filter_action' => '1',
        4 => '24',
        'field_type_id' => '24',
        5 => '',
        'system_field' => '',
        6 => '-1',
        'match_type' => '-1',
        7 => 'Jeronimo',
        'match_value' => 'Jeronimo',
        8 => '',
        'argument' => '',
      ),
    ),
    'settings' => 
    array (
    ),
  ),
  'XML Test - WeKiss' => 
  array (
    'partner' => 
    array (
      'id' => '53',
      'user_id' => '2',
      'created_at' => '2012-06-24 15:48:00',
      'wrapped_campaign_id' => NULL,
      'name' => 'XML Test - WeKiss',
      'create_from_tpl_id' => NULL,
      'posting_type' => '5',
      'success_keyword' => 'status="1"',
      'failure_keyword' => 'status="0"',
      'delivery_addr' => 'http://process.wekiss.com/coregistration',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => '<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE coregistration PUBLIC "-//Neteden//DTD Coregistration//EN"
"http://process.wekiss.com/coregistration.dtd">
<coregistration>
<user nickname="%nickname%" password="%password%" email="%email%"
birthday="%birthday%" city="%city%" degree="%degree%" comfrom="%comfrom%" test="0">
<postalCode>%postalCode%</postalCode>
<ip>%ip%</ip>
<tracker>%tracker%</tracker>
</user>
</coregistration> ',
    ),
    'fields' => 
    array (
      668 => 
      array (
        0 => '668',
        'id' => '668',
        1 => '53',
        'partner_id' => '53',
        2 => 'birthday',
        'name' => 'birthday',
        3 => '1972-01-01',
        'value' => '1972-01-01',
        4 => '',
        'modifier' => '',
      ),
      669 => 
      array (
        0 => '669',
        'id' => '669',
        1 => '53',
        'partner_id' => '53',
        2 => 'city',
        'name' => 'city',
        3 => 'Los Angeles',
        'value' => 'Los Angeles',
        4 => '',
        'modifier' => '',
      ),
      670 => 
      array (
        0 => '670',
        'id' => '670',
        1 => '53',
        'partner_id' => '53',
        2 => 'comfrom',
        'name' => 'comfrom',
        3 => '667444',
        'value' => '667444',
        4 => '',
        'modifier' => '',
      ),
      671 => 
      array (
        0 => '671',
        'id' => '671',
        1 => '53',
        'partner_id' => '53',
        2 => 'degree',
        'name' => 'degree',
        3 => '1',
        'value' => '1',
        4 => '',
        'modifier' => '',
      ),
      672 => 
      array (
        0 => '672',
        'id' => '672',
        1 => '53',
        'partner_id' => '53',
        2 => 'email',
        'name' => 'email',
        3 => 'ribicb@yahoo.com',
        'value' => 'ribicb@yahoo.com',
        4 => '',
        'modifier' => '',
      ),
      673 => 
      array (
        0 => '673',
        'id' => '673',
        1 => '53',
        'partner_id' => '53',
        2 => 'ip',
        'name' => 'ip',
        3 => '85.222.231.234',
        'value' => '85.222.231.234',
        4 => '',
        'modifier' => '',
      ),
      674 => 
      array (
        0 => '674',
        'id' => '674',
        1 => '53',
        'partner_id' => '53',
        2 => 'nickname',
        'name' => 'nickname',
        3 => 'ribicb',
        'value' => 'ribicb',
        4 => '',
        'modifier' => '',
      ),
      675 => 
      array (
        0 => '675',
        'id' => '675',
        1 => '53',
        'partner_id' => '53',
        2 => 'password',
        'name' => 'password',
        3 => 'sequ01a',
        'value' => 'sequ01a',
        4 => '',
        'modifier' => '',
      ),
      676 => 
      array (
        0 => '676',
        'id' => '676',
        1 => '53',
        'partner_id' => '53',
        2 => 'postalCode',
        'name' => 'postalCode',
        3 => '90210',
        'value' => '90210',
        4 => '',
        'modifier' => '',
      ),
      677 => 
      array (
        0 => '677',
        'id' => '677',
        1 => '53',
        'partner_id' => '53',
        2 => 'tracker',
        'name' => 'tracker',
        3 => 'xml-test',
        'value' => 'xml-test',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      160 => 
      array (
        0 => '160',
        'id' => '160',
        1 => '53',
        'partner_id' => '53',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  'XML1' => 
  array (
    'partner' => 
    array (
      'id' => '54',
      'user_id' => '2',
      'created_at' => '2012-05-07 22:48:37',
      'wrapped_campaign_id' => NULL,
      'name' => 'XML1',
      'create_from_tpl_id' => NULL,
      'posting_type' => '5',
      'success_keyword' => 'success',
      'failure_keyword' => 'fail',
      'delivery_addr' => 'http://w1.localhost/',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => 'fdg%em%%fn%',
    ),
    'fields' => 
    array (
      678 => 
      array (
        0 => '678',
        'id' => '678',
        1 => '54',
        'partner_id' => '54',
        2 => 'em',
        'name' => 'em',
        3 => '[Email]',
        'value' => '[Email]',
        4 => '',
        'modifier' => '',
      ),
      679 => 
      array (
        0 => '679',
        'id' => '679',
        1 => '54',
        'partner_id' => '54',
        2 => 'fn',
        'name' => 'fn',
        3 => '[First_Name]',
        'value' => '[First_Name]',
        4 => '',
        'modifier' => '',
      ),
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
      161 => 
      array (
        0 => '161',
        'id' => '161',
        1 => '54',
        'partner_id' => '54',
        2 => '1',
        'key' => '1',
        3 => '',
        'value' => '',
      ),
    ),
  ),
  '' => 
  array (
    'partner' => 
    array (
      'id' => '101',
      'user_id' => '2',
      'created_at' => '2013-04-23 16:07:32',
      'wrapped_campaign_id' => '44',
      'name' => '',
      'create_from_tpl_id' => NULL,
      'posting_type' => '0',
      'success_keyword' => '',
      'failure_keyword' => '',
      'delivery_addr' => '',
      'delivery_cap' => '0',
      'delivery_ctype' => '1',
      'parse_response' => '0',
      'delimiter' => '|',
      'success_url' => '',
      'price_per_lead' => '0',
      'should_retry' => '0',
      'username_failed_keyword' => '',
      'template' => NULL,
    ),
    'fields' => 
    array (
    ),
    'filters' => 
    array (
    ),
    'settings' => 
    array (
    ),
  ),
);

