<style>
<!--

#catchup-jobs tbody td, #catchup-jobs thead th {
    padding-left: 5px;
    padding-right: 5px;
}

#catchup-jobs tbody tr:hover {
    background-color: #eee7c7;
}

#catchup-jobs tfoot td {
    padding: 10px;
    color: #777;
    font-style: italic;
    text-align: center;
}

-->
</style>
<div class="head">
    <h2>Catchup Jobs</h2>
	<div class="breadcrumb">
		<p>
			<a href="/admin/">Administration &gt;</a> Catchup Jobs
		</p>
		<div class="clear"></div>
	</div>
</div>

<table id="catchup-jobs">
    <thead>
        <tr>
            <th>Campaign Name</th>
            <th>Partner Name</th>
            <th>User</th>
            <th>Initial Count</th>
            <th>In Queue</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
    <?php

    foreach ($jobs as $row) {
        echo "
        <tr>
            <td>" . escapeHtml($row['campaign_name']) . "</td>
            <td>" . escapeHtml($row['partner_name']) . "</td>
            <td>" . escapeHtml($usernamesAssoc[$row['user_id']]) . "</td>
            <td>$row[start_count]</td>
            <td>$row[in_queue]</td>
            <td><a href=\"deleteJob.html?id=$row[id]\">Cancel</a></td>
        </tr>\n";
    }

    if (empty($jobs)) {
        echo "<tfoot><tr><td colspan=\"4\">There Are No Catchup Jobs</td></tr></tfoot>";
    }

    ?>
    </tbody>
</table>