<style>

th {
	padding: 0 3px;
	text-align: center;
}

td {
	padding: 0 10px;
}

</style>

<div class="head"><h2>Export Feeds</h2></div>

<table style="margin-bottom: 20px;" class="data-table">
  <thead>
  <tr>
  <th>Name</th>
  <th>URL Key</th>
  </tr>
  </thead>

<?php

foreach ($list as $row) {
    echo "
  <tr>
    <td>" . escapeHtml($row['name']) . "</td>
    <td>" . escapeHtml($row['key']) . "</td>
    <td>" .
        App::linkFor($this, '<img src="' . Config::$urlBase . 'img/icons/pencil.png" style="margin-bottom: 2px;" /> <u>Edit</u>',       array('action' => 'edit'),    array('id' => $row['id']), 'style="text-decoration: none; ; margin-left: 30px;"') .
        App::linkFor($this, '<img src="' . Config::$urlBase . 'img/icons/delete.png" style="margin-bottom: 2px;" /> <u>Delete</u>',     array('action' => 'delete'),  array('id' => $row['id']), 'style="text-decoration: none; margin-left: 30px;" id="delete_' . $row['id'] . '"') .
    "</td>
  </tr>";
}

?>
</table>
<?php
if ($count > $perPage) {
    echo '<div class="pager">';
    Pager::showPager($count, $perPage);
    echo '</div>';
}

?>
<?php echo App::linkFor($this, '<img src="/img/icons/add.png" style="margin-bottom: 2px;" /> <span style="text-decoration: underline;">Add Export Feed...</span>', array('action' => 'add'), array(), 'style="text-decoration: none;"'); ?>

<script type="text/javascript">

$(document).ready(function() {
	$('a[id^="delete_"]').click(function(e) {
		e.preventDefault();
		if (confirm("Delete Export Feed?")) {
			var arr = $(this).attr('id').split('_');
			var id = arr[1];
			$.post(<?php echo "'" . App::getFrontController()->urlFor($this, array('action' => 'ajaxDelete')) . "'"; ?>,
					{'id' : id, '__nonce' : <?php echo "'" . Session::getSession()->getNonce() . "'"; ?>}, function (response) {
						if (response == 'OK') {
							document.location.reload(true);
						} else {
							alert(response);
						}
					});
		}
	});
});

</script>