<div class="head">
	<h2>Reports</h2>
	<div class="breadcrumb">
		<p><?php
		$arr = array('iid' => $incId);
		if (!empty($_GET['hide_repost'])) {
		    $arr['hide_repost'] = 1;
		}
		if (isset($_GET['o']['muid'])) {
		    $arr['uid'] = $_GET['o']['muid'];
		}
		echo App::linkFor($this, 'Associated Transactions', array('action' => 'index'), $arr); ?>&gt; Form Values</p>
	</div><!--breadcrumb-->
	<div class="breadcrumb"><?php
	echo $this->getIidPrevNext(str_replace('.phtml', '.html', basename(__FILE__)), !empty($_GET['iar']), $_GET['inc_id'], isset($_GET['delivery_id']) ? $_GET['delivery_id'] : '', !empty($_GET['hide_repost']),
	            (isset($_GET['o']) && is_array($_GET['o'])) ? $_GET['o'] : array(),
                (isset($_GET['iids'])) ? explode('-', $_GET['iids']) : array(),
                (isset($_GET['dids'])) ? explode('-', $_GET['dids']) : array());

	?></div>
</div><!--head-->

<div class="transaction">
	<table cellpadding="0" cellspacing="0">
	<tbody>
		<tr class="top">
			<td>Field Type</td>
			<td>Value</td>
		</tr>

<?php

$arr = array();
$missing = array();
$odd = false;
foreach ($values as $k => $v) {
    if (isset($campaignFields[$k])) {
        $arr[$campaignFields[$k]] = $v;
    } else {
        $missing[] = $k;
    }

    $odd = !$odd;
    $c = $odd ? 'white' : 'grey';
    echo "<tr class=\"$c\"><td>";
    echo isset($fieldTypes[$k]) ? escapeHtml($fieldTypes[$k]) : "$k";
    echo "</td><td>" . escapeHtml($v);
    echo "</td></tr>\n";
}
?>
	</tbody>
</table>
</div>
<?php return; ?><!-- transaction -->
<!--
<?php

if ($missing) {
    echo "!!! CAMPAIGN FIELDS MISSING : " . implode(", ", $missing) . " !!!\n\n";
}
echo "/api/$hashCode/?" . http_build_query($arr) . "\n\n\$_SERVER['REMOTE_ADDR'] = '$ipAddress';\n\n\$campaignid = $campaignId;";

?>


-->
