<style>

th {
	padding: 0 3px;
	text-align: center;
}

td {
	padding: 0 10px;
}

</style>

<div class="head"><h2>Industries</h2></div>

<table class="data-table">
  <thead>
  <tr>
    <th>Abbr.</th>
    <th>Name</th>
  </tr>
  </thead>

<?php

foreach ($list as $row) {
    echo "
  <tr>
    <td>" . escapeHtml($row['abbreviation']) . "</td>
    <td>" . escapeHtml($row['name']) . "</td>
    <td>" .
        App::linkFor($this, '<img src="' . Config::$urlBase . 'img/icons/pencil.png" style="margin-bottom: 2px;" /> <u>Edit</u>',      array('action' => 'edit'),    array('id' => $row['id']), 'style="text-decoration: none; ; margin-left: 30px;"') .
        App::linkFor($this, '<img src="' . Config::$urlBase . 'img/icons/delete.png" style="margin-bottom: 2px;" /> <u>Delete</u>',     array('action' => 'delete'),  array('id' => $row['id']), 'style="text-decoration: none; margin-left: 30px;"') .
    "</td>
  </tr>";
}

?>
</table>
<?php
if ($count > $perPage) {
    echo '<div class="pager">';
    Pager::showPager($count, $perPage);
    echo '</div>';
}

?><br>
<?php echo App::linkFor($this, '<img src="/img/icons/add.png" style="margin-bottom: 2px;" /> <span style="text-decoration: underline;">Add Industry...</span>', array('action' => 'add'), array(), 'style="text-decoration: none;"'); ?>