<style>

ul.report {
    margin: 10px 20px;
}

ul.report li {
    margin-bottom: 15px;
}

ul.report ul {
    margin-left: 20px;
}

#timezone-dialog {
    display: none;
}

#timezone-picker {
    cursor: pointer;
    color: #333;
    text-decoration: underline;
}

div.graph-img {
    height: 300px;
    width: 530px;
}

div.graph-img div {
    font-size: 30px;
    text-align: center;
}

h3.username {
    font-size: 20px;
    color: #fff;
    font-weight: bold;
    margin-bottom: 13px;
    background-color: #344a53;
    padding: 10px 40px;
}

</style>

<div class="head">
	<h2>Admin Dashboard - Campaigns With No Shadow Report</h2>
	<div class="breadcrumb">

		<p><a href="/admin/">Admin &gt;</a> <a href="/admin/dashboard/">Dashboard &gt;</a> Campaigns With no Shadows</p>

		<div class="clear"></div>
	</div><!--breadcrumb-->
</div>

<?php

foreach ($data as $userId => $dr) {

    echo "<h3 class=\"username\">" . escapeHtml($usernames[$userId]) . "</h3>\n";
    $campaigns  = $dr['campaigns'];
    $cStats     = $dr['cStats'];
    $partners   = $dr['partners'];
    $graphStats = $dr['graphStats'];

    foreach ($campaigns as $campaign) {
        $tStats = $cStats[$campaign['id']];

        ?>
    <div class="campaign">
    <h3>Campaign: <?php echo escapeHtml($campaign['name']); ?></h3>

        <div class="score">

    	<div class="activity">
    		<h5>Activity for last 24 hours</h5>
    		<p>&nbsp;
    		<span class="accepted"><span></span> &nbsp; Accepted </span>
    		<span class="rejected"><span></span> &nbsp; Rejected </span>
    		<span class="delivery"><span></span> &nbsp; Delivered </span>
    		</p>

    	</div><!--activity-->

    	<div class="graph">

    		<!-- <img style="width: 530px; height: 300px;" src="activityGraph.html?campaign_id=<?php echo $campaign['id']; ?>"/> -->
    		<div class="graph-img" id="graph-img-<?php echo $campaign['id']; ?>"><div><?php
    		$cs = $graphStats[$campaign['id']];
    		if ((array_sum($cs['inc-0']) + array_sum($cs['inc-1']) + array_sum($cs['out-1'])) == 0) {
    		    echo 'No Data Available';
    		} else {
    		    echo 'Pending...';
    		}
    		?></div></div>


    	</div><!--graph-->
    	<div class="total">

    		<div class="number">
    			<p>Received: <span><?php echo number_format($tStats['accepted'])?></span></p>
    		</div><!--number-->

    		<div class="number">
    			<p>Delivered: <span><?php echo number_format($tStats['delivered'])?></span></p>
    		</div><!--number-->

    		<div class="clear"></div>
    	</div><!--total-->

    	<img class="pointer" src="/images/pointer-right.jpg"/>
    	<div class="clear"></div>
        </div><!-- score -->

    	<div class="stats">
    		<div class="top">
    			<h4>Campaign Summary: <?php echo escapeHtml($campaign['name']); ?></h4>
    		</div><!--top-->

    		<table class="days" cellpadding="0" cellspacing="0">
    			<tbody>
    				<tr class="top">
    					<td class="first"></td>
    					<td>Today</td>
    					<td>Yesterday</td>
    					<td>7 Days</td>
    					<td>30 Days</td>
    				</tr>
    				<tr class="datarow">
    					<td class="first">Accepted</td>
    					<td><?php echo number_format($tStats['t']['a']); ?></td>
    					<td><?php echo number_format($tStats['y']['a']); ?></td>
    					<td><?php echo number_format($tStats['7']['a']); ?></td>
    					<td><?php echo number_format($tStats['30']['a']); ?></td>
    				</tr>
    				<tr class="grey datarow">
    					<td class="first">Rejected</td>
    					<td><?php echo number_format($tStats['t']['r']); ?></td>
    					<td><?php echo number_format($tStats['y']['r']); ?></td>
    					<td><?php echo number_format($tStats['7']['r']); ?></td>
    					<td><?php echo number_format($tStats['30']['r']); ?></td>
    				</tr>
    				<tr>
    					<td class="first">&nbsp;</td>
    					<td>&nbsp;</td>
    					<td>&nbsp;</td>
    					<td>&nbsp;</td>
    					<td>&nbsp;</td>
    				</tr>
    			</tbody>
    		</table>

    		<table class="partners" cellpadding="0" cellspacing="0">
    			<tbody>
    				<tr class="top">
    					<td class="first">Partner</td>
    					<td>Success</td>
    					<td>Decline</td>
    				</tr>

    <?php

    $pd = $tStats['pd'];
    $pdata = array();
    foreach ($pd as $pid => $row) {
        if (isset($partners[$pid])) {
            $pdata[$partners[$pid]] = $row;
        }
    }
    ksort($pdata);
    $c = 'white';
    foreach ($pdata as $pName => $row) {
        $pName = escapeHtml($pName);
        $succ = number_format(isset($row[1]) ? $row[1] : 0);
        $fail = number_format(isset($row[0]) ? $row[0] : 0);
        echo "
    				<tr class=\"$c\">
    					<td class=\"first\" title=\"$pName\">$pName</td>
    					<td>$succ</td>
    					<td>$fail</td>
    				</tr>";
        $c = ($c == 'grey') ? 'white' : 'grey';
    }

    if ($pdata) {
    ?>
    				<tr class="<?php echo $c; ?>">
    					<td class="first">&nbsp;</td>
    					<td>&nbsp;</td>
    					<td>&nbsp;</td>
    				</tr>
    <?php } else {?>
    				<tr class="<?php echo $c; ?>">
    					<td class="first" colspan="3" style="padding-left: 200px;">No Data</td>
    				</tr>
    <?php } ?>
    			</tbody>
    		</table>

    		<p class="details"><a href="/reporting/?from=<?php echo urlencode(date('m/d/Y')); ?>&to=<?php echo urlencode(date('m/d/Y')); ?>&cid=<?php echo $campaign['id']; ?>&cst=0&pid=0&sst=0">SEE DETAILS</a></p>

    		<div class="clear"></div>
        </div><!-- stats -->
    <div class="clear"></div>
    </div>



    <?php }?>
<script type="text/javascript">

function drawAllCharts_<?php echo $userId; ?>() {
    var options = {
      backgroundColor: '#fff',
      lineWidth: 1,
      chartArea: {width: '100%', height: '93%', top: 0},
      titlePosition: 'none',
      colors: ['#f6851f', 'red', '#293f4a'],
      axisTitlesPosition: 'in',
      hAxis: {textPosition: 'out', textStyle: {fontSize: 10}},
      vAxis: {textPosition: 'in',  textStyle: {fontSize: 10}, minValue: 0},
      legend: {
          position: 'none'
      }
    };

    <?php

    foreach ($graphStats as $cid => $gs) {
        if ((array_sum($gs['inc-1']) + array_sum($gs['inc-0']) + array_sum($gs['out-1'])) == 0) {
            continue;
        }
        echo "\n\t\tvar data = google.visualization.arrayToDataTable([
          ['Hour', 'Accepted', 'Rejected', 'Delivered']";
        foreach ($gs['inc-1'] as $k => $v) {
            $k2 = trim($k);
            echo ",
          ['$k2', $v, {$gs['inc-0'][$k]}, {$gs['out-1'][$k]}]";
        }
        echo "
          ]);";
        // echo '/*'; var_export($gs); echo '*/';
        echo "
        var chart = new google.visualization.LineChart(document.getElementById('graph-img-$cid'));
        chart.draw(data, options);\n";
    }
?>

};
</script>
<?php



    // echo "<li>" . escapeHtml($usernames[$userId]);
    // echo "<ul style=\"margin-bottom: 0;\">";
    // foreach ($arr as $oneCampaign) {
    //     echo "<li>&bull; " . App::linkFor('Campaigns', escapeHtml($oneCampaign['name']), array('action' => 'edit'), array('id' => $oneCampaign['id'])) . "</li>";
    // }
    // echo "</ul>";
    // echo "</li>";
}

?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

google.load("visualization", "1", {packages:["corechart"]});

$(document).ready(function() {
	$('#timezone-picker').click(function() {timezonePicker($(this));});
	<?php
	foreach ($data as $userId => $x) {
	    echo "\n\tdrawAllCharts_$userId();";
	}
?>

});



</script>
